config/routes.rb
FiWareIdm::Application.routes.draw do
  # FIWARE compatible routes
  match '/authorize', to: 'authorizations#new'
  post  '/token', to: proc { |env| SocialStream::Oauth2Server::TokenEndpoint.new.call(env) }

  devise_for :users, :controllers => {:omniauth_callbacks => 'omniauth_callbacks', registrations: 'user_registrations'}

  namespace :permission do
    resources :customs
  end

  resources :purchases
  resources :roles

  #Role Assignment. REST API
  match '/applications/:app_id/actors' => "applications#index_actors", :via => :get, :format => :json
  match '/applications/:app_id/actors' => "applications#create_actor", :via => :post, :format => :json
  match '/applications/:app_id/actors/:actor_id' => "applications#show_actor", :via => :get, :format => :json
  match '/applications/:app_id/actors/:actor_id' => "applications#update_actor", :via => :put, :format => :json
  match '/applications/:app_id/actors/:actor_id' => "applications#delete_actor", :via => :delete, :format => :json

  #Authentication Token API
  namespace :api do
    namespace :v1  do
      resources :tokens,:only => [:create, :destroy]
    end
  end

  #SCIM 2.0 API
  namespace :v2 do
    resources :users
    resources :organizations
    match '/ServiceProviderConfigs' => "base#getConfig"
    match '/testing' => "base#testing"
  end

  match '/terms-of-service' => 'frontpage#terms_of_service', as: :terms_of_service
end

app/views/home/_applications.html.erb
<div class="applications">
  <header>
    Applications
    <%= link_to "Register", new_application_path %>
  </header>

  <% if current_subject.applications.blank? %>
    <%= render partial: 'applications/first'%>
  <% else %>
    <%= render partial: 'site/clients/list',
               object: current_subject.applications.first(5) %>

    <%= link_to 'View all', applications_path, :class => "view-all" %>
  <% end %>
</div>

app/views/home/_members.html.erb
<div class="members">
  <header>
    Members

    <%= render partial: "contacts/add_button",
               locals: {
                 sender: current_subject,
                 type: :user
               }
    %>
  </header>

  <%= render current_subject_contacts(current_subject).first(5) %>
  
  <%= link_to 'View more',  contacts_path, :class => "view-all"  %>
</div>

app/views/home/_organizations.html.erb
<div class="organizations">
  <header>
    Organizations
    <%= link_to "Create", new_organization_path %>
  </header>

  <!--
  <form class="form-inline">
    <input type="text" class="input-small" placeholder="search..">
  </form>
  -->

  <% if current_user.organizations.blank? %>
    <div class="first-time-message">
      <h3>  
        You are not member of any organization
      </h3> 
      <%= link_to "Browse organizations", organizations_path(section: 'others') %> or <%= link_to "create a new organization", new_organization_path %>
    </div>
  
  <% else %>
    <%= render partial: 'organizations/list',
               object: current_user.organizations.first(5) %>

    <%= link_to "View all", organizations_path, :class => "view-all" %>
  <% end %>
</div>

app/views/home/index.html.erb
<div id="home">
  <div class="home">
    <%= render partial: 'home/applications' %>

    <% if current_subject.is_a? User %>
      <%= render partial: 'home/organizations' %>
    <% else %>
      <%= render partial: 'home/members' %>
    <% end %>
  </div>
</div>