config/routes.rb
FiWareIdm::Application.routes.draw do
  # FIWARE compatible routes
  match '/authorize', to: 'authorizations#new'
  post  '/token', to: proc { |env| SocialStream::Oauth2Server::TokenEndpoint.new.call(env) }

  devise_for :users, :controllers => {:omniauth_callbacks => 'omniauth_callbacks', registrations: 'user_registrations'}

  namespace :permission do
    resources :customs
  end

  resources :purchases
  resources :roles

  #Role Assignment. REST API
  match '/applications/:app_id/actors' => "applications#index_actors", :via => :get, :format => :json
  match '/applications/:app_id/actors' => "applications#create_actor", :via => :post, :format => :json
  match '/applications/:app_id/actors/:actor_id' => "applications#show_actor", :via => :get, :format => :json
  match '/applications/:app_id/actors/:actor_id' => "applications#update_actor", :via => :put, :format => :json
  match '/applications/:app_id/actors/:actor_id' => "applications#delete_actor", :via => :delete, :format => :json

  #Authentication Token API
  namespace :api do
    namespace :v1  do
      resources :tokens,:only => [:create, :destroy]
    end
  end

  #SCIM 2.0 API
  namespace :v2 do
    resources :users
    resources :organizations
    match '/ServiceProviderConfigs' => "base#getConfig"
    match '/testing' => "base#testing"
  end

  match '/terms-of-service' => 'frontpage#terms_of_service', as: :terms_of_service
end

app/views/frontpage/_presentation.html.erb
<article id="presentation">
  <script>
    var confirm_help_box = function () {
      var r = confirm("The communications sent to the GBerry support list are public and they generate public tickets. Please avoid sending private info unless you are happy to see it publicly available.");
      if (r == true) {
          window.location = "mailto:project@gberry.xyz?Subject=GBerry Support";
      } 
    }
   </script>
  <section class="media">
    <h3 class="media-heading">
      GBerry - Fun Together!
    </h3> 
    <span>
      GBerry is multiplayer game console platform for your living room. 
    </span>
    <p>
      You will be able to create your own user account for GBerry platform.
    </p>
    <div class="sign_up">
      <%= link_to t('devise.links.sign_up'), new_registration_path(resource_name) %>
    </div>
  </section>

   <section class="help-bar">
   <!-- TODO: This code is left for reference how to get help pages (urls been todoed)
        <div style="cursor: pointer;" class="help-box" onclick="confirm_help_box()">
            <header>
              <img src="/assets/help.png">
              <h5>Need Help?</h5>
              <i class="icon-chevron-right icon-white"></i>
            </header>
          <div>
            Ask a question.
          </div>
        </div>

        <div class="help-box">
          <a target="_blank" href="http://TODO">
            <header>
              <img src="/assets/ges.png">
              <h5>Our GEs</h5>
              <i class="icon-chevron-right icon-white"></i>
            </header>
          </a>  
          <div>
            See our Catalogue.
          </div>
        </div>

        <div class="help-box">
          <a target="_blank" href="TODO">
            <header>
              <img src="/assets/fi-ops.png">
              <h5>FIWARE Lab nodes</h5>
              <i class="icon-chevron-right icon-white"></i>
            </header>
          </a>
          <div>
            Learn about FIWARE Ops.
          </div>
        </div>

        <div class="help-box">
          <a target="_blank" href="http://TODO/">
            <header>
              <img src="/assets/more-info.png">
              <h5>eLearning</h5>
              <i class="icon-chevron-right icon-white"></i>
            </header>
          </a>
          <div>
            Train yourself.
          </div>
        </div>
  -->
      </section>
     
</article>

app/views/frontpage/_presentation_default.html.erb
<section>
  <article class="media">
    <a class="pull-left" href="#">
      <img class="media-object" data-src="holder.js/64x64" alt="identify" style="width: 64px; height: 64px;" src="/assets/user-front.png">
    </a>
    <div class="media-body">
      <h3 class="media-heading">
        Identity Manager
      </h3>
      The platform contains lots of users and organizations working together to achieve this great infrastructure network.
     </div>
  </article>
</section>

app/views/frontpage/terms_of_service.html.erb
<section id="terms_of_service">
  <%= render partial: 'toolbar/terms_of_service'%>
<section>